name: agir-eu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - openai>=1.14.0
    - tqdm>=4.66.1
    - python-dotenv>=1.0.0
    - httpx>=0.27.0
    - pandas>=2.0.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0 